# Generated by Django 5.0.4 on 2024-05-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Blog',
        ),
    ]
